### PR TITLE
Added Should.Throw(Task) overloads

### PR DESCRIPTION
**Pull request by JoeMighty**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
I am going to close this, I am giving the Should.Throw stuff a fair overhaul for #195 and have added these overloads as well as the custom messages.

Thanks though!

**Comment by JoeMighty** [comment]
Alright, no problem!

**Comment by JakeGinnivan** [comment]
I did just open some message generator issues if you were itching to submit pull requests :P

**Comment by JoeMighty** [comment]
I sure am! I'll take a look at them :) I'm really enjoying contributing.

**Pull request closed without merging**
