### PR TITLE
Added more ReSharper contract annotations

### PR DESCRIPTION
**Pull request by skrysmanski**
This pull request adds ReSharper contract annotations (like in #134) to more methods.

### CODE REVIEW

**Comment by skrysmanski** [comment]
Not sure what I should do about this failing test.

**Comment by JosephWoodward** [comment]
Sorry it's taken me a while to get around to this, I'm not sure what's happening yet but I'll take a look and get this merged as soon as I can 👍

**Comment by Roemer** [comment]
Will this be merged somewhere soon?

**Comment by JosephWoodward** [comment]
Yes, it will be. I'm just trying to migrate from project.json to the new .csproj format before I merge anymore PRs. Hoping to have it sorted soon!

**Comment by JosephWoodward** [comment]
Finally got around to merging the project.json to .csproj changes so can merge this, thanks for your contribution @skrysmanski, sorry it's taken me so long!

**Pull request merged**
