### PR TITLE
Switching to AppVeyor for builds

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by gep13** [comment]
Thinking about it...

Do you actually need the matrix to complete this?  Can you not simply run the build twice, on the same machine, each targetting the correct version of the .Net Framework?

I would suggest that the use of some build script would be easier to achieve this.

**Comment by JakeGinnivan** [comment]
Yeah, thats what I am thinking. Would be good to support multiple projects/steps in a single appveyor build, but for the moment will just do a simple build script which just calls msbuild twice

**Comment by gep13** [comment]
You can do multiple steps just now in a yml file, you would just need to "own" some more of it, and not rely on AppVeyor calling MSBuild for you, i.e. make it your build step that calls into msbuild directly

**Comment by JakeGinnivan** [comment]
How do you do that, I couldn't see that feature documented. Saw that for before/after build but not a build step

**Comment by gep13** [comment]
Have a look here:

https://github.com/gep13/gep13.github.io/blob/source/appveyor.yml

``build_script``` section

**Comment by gep13** [comment]
granted, that was for building an Octopress site. but don't see why the same principal couldn't be applied to your msbuild steps.

**Pull request merged**
