### PR TITLE
Issues/174   improve should contain error message

### PR DESCRIPTION
**Pull request by JakeGinnivan**
#178 rebased and manually merged - work done by @urig

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
@urig there was a Hackathon event and I ended up merging a conflicting PR, yours stuff adds a bunch of tests and highlights some other things (like the negative condition I missed in the code review of the other).

Did you want to have a look over this to make sure all the changes make sense?

**Comment by JakeGinnivan** [comment]
I put the additional two commits on as I haven't responded to you and did not want to mess you around :)

**Comment by JakeGinnivan** [comment]
If you have questions about rebasing or anything just ask, will walk you through what I have done

**Comment by JakeGinnivan** [comment]
In fact. Gonna merge this now. master has tests failing. If you see anything feel free to open another PR :)

**Comment by urig** [comment]
Thanks @JakeGinnivan :). Sorry for having disappeared - did not pay enough attention to gmail over the weekend. (Addicted to twitter though so a lot more attentive there).

**Comment by JakeGinnivan** [comment]
No probs. Was not time critical or anything :)

**Pull request merged**
