### PR TITLE
Fix #273

### LINKED ISSUE #273: Implement ShouldBePositive() and ShouldBeNegative() for numeric types with sign
See #269 

ShouldBeNegative():
Asserts that the numeric value is less than zero.

ShouldBePositive():
Asserts that the numeric value is greater than or equal to zero.

### PR DESCRIPTION
**Pull request by gertnelissen**
Added extension methods ShouldBePositive and ShouldBeNegative for data types int, short, long, float, double and decimal. I've provided a message generator for each of the extension method types so the assertion failed message should be clear.

### CODE REVIEW

**Comment by JoeMighty** [comment]
Thanks for the pull request. I've just noticed the new extensions are missing the `Func<string>` delegate overloads for the customMessage parameter. Are you able to add those please?

**Comment by gertnelissen** [comment]
I've added them + unit tests for these methods. I use the ShouldBeGreatherThan/ShouldBeLessThan extension methods so they are now implicitly tested as well.

As for documentation like @JakeGinnivan asked; is the first comment on this pull request clear enough?

**Comment by gertnelissen** [comment]
Just a *ping* to notify the owners that this is ready and still waiting for confirmation.

**Comment by JoeMighty** [comment]
Thanks @gertnelissen. It all looks good for me, though given the size of the pull request I'll wait for @JakeGinnivan to have a look over it as he's pretty good and picking up on things I may have missed.

**Comment by JakeGinnivan** [comment]
I am in Dallas at the moment for a conference, I should have time once I get to Austin (Wednesday).

Sent from my Windows Phone
________________________________

**Comment by JakeGinnivan** [comment]
Amazing work @gertnelissen! Thanks heaps

**Pull request merged**
