### PR TITLE
Reworks docs to use Spinx and Rst

### PR DESCRIPTION
**Pull request by enkafan**
Reworked the documentation to use Sphinx and reStructuredText markup
rather than mark down.

 * Added a contributing page on how to get this to build locally (you're
   gonna need python) as well as a style guideline
 * Converted the shouldBe and shouldNotBe documentation to reST
 * Added a simple example of bringing in source from an external file in
   the shouldBe documentation.

The example file pulls right from the unit test. I originally was going to
create a seperate project for just documentation purposes, but the
existing unit tests are so close that I didn't want to go down that route
without further input. Seems like some slight tweaking to the existing
unit tests on the formatting (and to throw in some Simpsons references)
and they could be used for the docs too.

Ultimately I think a "documentation" project will be needed. Little things
like referencing which line numbers to bring in would make working with
the unit test project and adjusting the using statements or adding a
comment could throw off the documentation.

### CODE REVIEW

**Comment by enkafan** [comment]
Looks like this PR ha gotten behind. I was going to merge in the content added by @JoeMighty but before I go down that route I wanted to make sure that 1) no other content was in the queue to be merged and 2) this is still something to be considered for doing.

**Comment by JakeGinnivan** [comment]
I am keen for it to go in, I have just been distracted on other things. @JoeMighty?

**Comment by JoeMighty** [comment]
Me too! I'm looking forward to seeing this.

**Comment by enkafan** [comment]
Got the TimeSpan docs merged in and things look all set to be switched over. Not sure what has to be tweaked on the RTD side of things for it to see the change. I'm curious how that transition will go

**Pull request merged**
