### PR TITLE
Adds Should(Not)BeNullOrWhiteSpace for strings

### PR DESCRIPTION
**Pull request by i3arnon**
Adds ShouldBeNullOrWhiteSpace and ShouldNotBeNullOrWhiteSpace extension
methods for strings based on String.IsNullOrWhiteSpace

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Hey @i3arnon 

Thanks for the PR, I have been moving countries so it took me longer than I would like to get to this. `string.IsNullOrWhiteSpace` is only available for > .net 4.0 so the .net 3.5 build is failing.

Would you be able to:
1) Wrap the contents of `StringNullOrWhiteSpaceTestExtensions.cs` with `#if net40`/`#endif#`
2) Move the message generator into the `#if net40` section
3) Wrap the test classes with `#if net40`/`#endif#`

Since this PR was sent I have fixed up the build so you will get feedback directly on the PR when you update it. If you are unable to update it let me know.

It would also be great if you could rebase this PR as the PR branch won't have the appveyor.yml file so I am not sure if the PR will build properly. If you need a hand rebasing just let me know, I can help you with the commands.

Thanks!

**Comment by JakeGinnivan** [comment]
Hope you don't mind, I am rebasing this and fixing the PR in another PR. Rebase still leaves you as the author of the commit.

**Comment by i3arnon** [comment]
@JakeGinnivan  No, sure.. as long as it gets in. Thanks.

**Comment by JakeGinnivan** [comment]
Yep, the new PR is at https://github.com/shouldly/shouldly/pull/251 so it will go out next release.

Sent from my Windows Phone
________________________________

**Pull request closed without merging**
