### PR TITLE
Merged pull request #355 from bangsholt:AddEnumHaveFlag

### PR DESCRIPTION
**Pull request by JosephWoodward**
These couldn't be merged automatically so I did it manually, I hope it's ok.

### CODE REVIEW

**Comment by JosephWoodward** [comment]
Is it possible to clean up the commit history before merging this one? I'd be interested to know how if it is for future purposes.

**Comment by JakeGinnivan** [comment]
@JosephWoodward `git rebase upstream/master` will remove all the merge commits. You will have to re-resolve any resoved merge conflicts. 

Or did you want to squash commits down too? If so `git rebase upstream/master -i` will do an interactive rebase where you can squash commits

**Comment by JosephWoodward** [comment]
Oh great, thanks! I've quite limited experience with rebasing as people keep telling me it can be dangerous (only ever done it via rebase -i HEAD~x), I'll try these out.

Out of interest, in this instance would you rather keep the history (minus the merge commits), or squash them down?

**Comment by JakeGinnivan** [comment]
I like keeping history normally, unless it goes back and forth and the history takes away from understanding how you got somewhere

**Comment by JosephWoodward** [comment]
Ok, that sounds good to me - thanks.

**Comment by JakeGinnivan** [comment]
Just remember, don't rewrite history now this is merged :) You need to rebase before you do the merge.

**Comment by JosephWoodward** [comment]
Haha, don't worry - I won't :) Though presumably I could providing no one has updated their local branches? (I suppose I'd also have to force push the changes?)

**Comment by JakeGinnivan** [comment]
Yeah, technically you can. But the etiquette is that PR branches, assume they have been rebased (reset rather than merge, or merge with --ff-only). So if it's a branch in your fork, force push away. If it's a branch in the main repo, don't force push. Just saves headaches later as the original commits always seem to keep coming back

**Comment by JosephWoodward** [comment]
Ok, thanks for the clarification. Just so you know I have no intention of ever doing that, I was just interested to see if it aligns with the way I imagined it working.

Would you mind expanding on what you mean when you say "reset rather than merge"?

**Comment by JakeGinnivan** [comment]
If you have a branch checked out, then someone rebases that branch and force pushes. If you update your local branch with `git merge remote/branch` then you will end up with conflicts and duplicated commits.

You can just go `git reset --hard remote/branch` to move your local branch HEAD to point at the remote branch Tip.

**Comment by JosephWoodward** [comment]
Gotcha, I see what you mean - thanks!

**Pull request merged**
