### PR TITLE
 Removed irrelevant stack frames from exception stack traces

### LINKED ISSUE #420: Filter stack trace
## Summary

Filter the stack trace of `ShouldAssertException` to remove all lines that occur within the testing framework, like it is done in the [should](https://github.com/erichexter/Should/blob/master/src/Should.Core/Exceptions/AssertException.cs#L69) library.

## Details

Consider the following test

```cs
 [Fact]
 public void Test()
 {
     new[] { 1, 2 }.ShouldContain(3);
 }
```

Currently the test failure report looks like this
```
Result StackTrace:	
   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, T expected, Func`1 customMessage) in ...\ShouldBeEnumerableTestExtensions.cs:line 27
   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, T expected) in ...\ShouldBeEnumerableTestExtensions.cs:line 16
   at UnitTestProject1.UnitTest1.Test() in ...\UnitTest1.cs:line 13
Result Message:	
Shouldly.ShouldAssertException : new[] { 1, 2 }
    should contain
3
    but was actually
[1, 2]
```

Note the useless top two stack frames. I suggest to make it look like this:

```
Result StackTrace:
	at UnitTestProject1.UnitTest1.Test() in ...\UnitTest1.cs:line 13
Result Message:	
Shouldly.ShouldAssertException : new[] { 1, 2 }
    should contain
3
    but was actually
[1, 2]
```

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #420

### CODE REVIEW

**Comment by jnm2** [comment]
@JosephWoodward This test intermittently fails but it also fails intermittently on your master branch:

```
     Shouldly.ShouldCompleteInException : 
Task
    should complete in
00:00:00.5000000
    but did not
      ---- Shouldly.ShouldlyTimeoutException : The operation has timed out.
      Stack Trace:
        C:\projects\shouldly\src\Shouldly.Tests\ShouldNotThrow\FuncOfTaskOfTWithTimeoutScenario.cs(43,0): at Shouldly.Tests.ShouldNotThrow.FuncOfTaskOfTWithTimeoutScenario.ShouldPass()
```

In the face of parallelism and especially with CI on a shared host, when the timeout is really for testing logic rather than precise timing, I usually start timeouts at ten seconds. A passing test won't take that long.

**Comment by jnm2** [comment]
@JosephWoodward When you have a free moment, can you look in on this or help me CC the right folks? Thanks!

**Comment by otto-gebb** [comment]
No reaction in a month. The project seems to be dead.

**Comment by JosephWoodward** [comment]
@otto-gebb It's not dead, unfortunately I don't work on Shouldly full time, not do I get paid to work on it. I help maintain Shouldly in my spare time - something I've not had much of lately that's all. Sometimes a bit of patience is required.

**Comment by JosephWoodward** [comment]
@jnm2 Thanks for this, it's a great addition to Shouldly, sorry it's taken me so long to getting around to it, life's been pretty hectic over the past few months!

**Comment by jnm2** [comment]
Thank you! Hey, have you considered looking for a second maintainer? I can't put myself forward because I'm so busy myself, but if someone is willing, we could take advantage of that. (I think the .NET Foundation can help with this, too.)

**Pull request merged**
