### PR TITLE
Switch to dotnet cli RC2 Preview 1 Tooling

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
@JosephWoodward I think this is pretty much done. I am still going to introduce Cake to do the builds which should fix the build issues.

Let me know if this all works for you or if you have any suggestions

**Comment by JosephWoodward** [comment]
@JakeGinnivan Great! I was hoping to have helped you and sat down last night to have a look at it but wasn't sure where to start.

**Comment by JakeGinnivan** [comment]
I got some help while at NDC, made it easier to get started

**Comment by khellang** [comment]
Nice! That looks like a pretty clean port :smile: I'don't proyally ignore the lockfiles though.

**Comment by JakeGinnivan** [comment]
@khellang yeah, most of the hard work was making it PCL which was 2.7.0 (which worked with RC1 I am pretty sure). Just switched to feature flags and cleaned a few things up.

The problem with not committing lock files is like not doing npm shrinkwrap right? Your transitive dependencies float? Is there a good workflow for updating transitive deps?

**Comment by khellang** [comment]
When you push to NuGet, your dependencies are fixed, I think. So there's no way for transitive dependencies to float. I also think doing a `dotnet restore` might overwrite your lockfiles at any time anyway. There's no way of _actually_ locking them (hint: they're not really a lockfile :stuck_out_tongue:). It's usually just noise when you're checking them in.

**Comment by JakeGinnivan** [comment]
Ok, I think this is ready to go. Am heading to bed but will merge and try and get a (automated) release out tomorrow :)

Any thoughts on where I should put the deployment process so any contributors can push it out?

**Comment by JosephWoodward** [comment]
Awesome work Jake! :+1: :+1:

**Comment by khellang** [comment]
:tada: :clap: :cake: :balloon: :grin: :dancers:

**Comment by JakeGinnivan** [comment]
:shipit:

**Comment by JakeGinnivan** [comment]
bet that bites me

**Pull request merged**
