### PR TITLE
Feature  #172

### LINKED ISSUE #172: Add `Should.ThrowAsync` method
Current `Should.Throw` is blocking. We should add a `Should.ThrowAsync` which returns a task and requires awaiting.

### PR DESCRIPTION
**Pull request by YogirajA**
I made an attempt to resolve #172. I have added two tests that are currently passing. Please let me know if you have any specific concerns, I will fix them.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Code looks good. Might be good to squash these commits down into 1 commit.

I will merge once #195 is done (might be a little while)

**Comment by YogirajA** [comment]
I will try to fix the the commits. Thanks!

**Comment by YogirajA** [comment]
I tried squashing the commits but changes being already pushed to remote, it was creating some minor conflicts and adding more commits (back to the problem). It might work out better at your end. If not, I can redo the changes as they are small enough. Let me know. Thanks

**Comment by JakeGinnivan** [comment]
Have rebased and squashed into a single commit, merged at 4445f828077832cad6fabbcd686cb0813afefecb

Thanks for the pull request!

**Pull request closed without merging**
