### PR TITLE
Fixed null string comparison

### LINKED ISSUE #499: ShouldBe difference text confuses null with the string "null"
To pick an amusing example:

```cs
string text = null;
text.ShouldBe("null");
```

Produces:
```cs
Shouldly.ShouldAssertException : text
    should be
"null"
    but was
null
    difference
Difference     |                     
               |                     
Index          | 0    1    2    3    
Expected Value | n    u    l    l    
Actual Value   | n    u    l    l    
Expected Code  | 110  117  108  108  
Actual Code    | 110  117  108  108  
```

The diff says it is comparing against actual char codes 110, 117, 108, and 108. I wouldn't expect a diff at all because the actual string is not present (in contrast, I do expect the diff that shows up for an empty string).

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #499.

### CODE REVIEW

**Comment by jnm2** [comment]
Something has gone rather wrong with CI:

```
Running .NET Core 2.0 tests for framework netcoreapp2.0...
Cake.exe : The specified framework version '2.0' could not be parsed
At line:1 char:1
+ & "C:\projects\shouldly\tools\Cake\Cake.exe" "build.cake" -target="De ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The specified f...d not be parsed:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
T
he specified framework 'Microsoft.NETCore.App
'
, ver
si
on '
2.0' was
 no
t 
found.
```

**Comment by JosephWoodward** [comment]
@jnm2 Yeah, not too sure what's happened there, will take a look at it this weekend then get this merged.

**Comment by JosephWoodward** [comment]
Looks like it's broken due to #536

**Comment by JosephWoodward** [comment]
Merged, thanks for this.

**Pull request merged**
