### PR TITLE
Better expression printing

### PR DESCRIPTION
**Pull request by ByteBlast**
This is my attempt at solving issue #185.

Please let me know if I misunderstood or if something needs changing.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
To be painful, I thought I would pull this class into it's own library and put on NuGet.

Could you switch over to https://github.com/JakeGinnivan/ExpressionToString

Sorry about that, but means we don't need the tests for the ExpressionStringBuilder and such

**Comment by JakeGinnivan** [comment]
It's a source package on nuget `ExpressionToString` or https://www.nuget.org/packages/ExpressionToString

**Comment by ByteBlast** [comment]
No problem.

Please check out the referenced issue first. Thank you.

**Comment by ByteBlast** [comment]
Done :smile:

**Comment by ByteBlast** [comment]
Should I add `App_Packages` to `.gitignore` or are you happy for it to reside in the solution?

**Comment by JakeGinnivan** [comment]
It gets checked in. This nuget package is a source only package. Just a lot more light weight :)

Sent from my Windows Phone
________________________________

**Comment by ByteBlast** [comment]
Yeah, I know - I just wanted to confirm. If there's anything more I can do,
please let me know.

**Comment by JakeGinnivan** [comment]
Nice work, if we add more expression overloads to things this will be really helpful

**Pull request merged**
