### PR TITLE
Dnx

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Initial port to Dnx.

Builds on #335, that needs to be merged first. To view actual changes see https://github.com/shouldly/shouldly/compare/JakeGinnivan:0057e3b3eabc5010f1e57f7e0ef5f321f8a58b3b...JakeGinnivan:Dnx

TODO

 - [ ] Restore conventiontests
 - [ ] Restore public API tests
 - [ ] Fix build

### CODE REVIEW

**Comment by JosephWoodward** [comment]
Out of interest, what's the plan of action for the convention test libraries that do not currently support DNX?

**Comment by JakeGinnivan** [comment]
Gonna have a crack at porting it, hopefully not too hard

**Comment by JakeGinnivan** [comment]
@JosephWoodward looks like the IsWithApprovedExceptions feature will drop out of coreclr due to missing approval tests on coreclr. Maybe this is the trigger for creating `str.ShouldMatchApproved()` :P

**Comment by JakeGinnivan** [comment]
//cc @dennisroche

**Comment by JakeGinnivan** [comment]
Superseeded by #341 

DNX tooling cannot do what we need at the moment, need to go with PCL/Shared libraries approach

**Pull request closed without merging**
