### PR TITLE
Added example classes to help with documentation

### PR DESCRIPTION
**Pull request by chaitanyagurrapu**
Hi @JakeGinnivan 
Based on our discussion in #349 here is the updated documentation. While I was at it, I also updated most of the other docs as mentioned in #308.

I haven't done strings yet. And looking at the "Exceptions" section there doesn't seem to be a Func<T> in shouldly, only Func<Task>. And I am not entirely clear on what you mean by "ShouldThrow extension method". I haven't done the "ShouldThrowAsync" either.

I wanted to submit this PR before it got too big for review and to make sure I was still following the intended roadmap regarding documentation. It seems to be generating the right .txt files under "src\DocumentationExamples\CodeExamples", but I haven't got the full documentation tool chain set up so I can't see it all laid out. Also not sure if the "docs\assertions\*.rst" files need to be created for each one or if they are generated as part of the build/deploy chain somewhere.

### CODE REVIEW

**Comment by JosephWoodward** [comment]
Awesome work :+1: It looks good from what I can see. Are you able to commit the generated text files too? I'm happy to make a start on adding the .rst docs for them.

**Comment by chaitanyagurrapu** [comment]
Done @JosephWoodward .

Although it seems like one of the shouldly methods (ShouldCompleteIn) seems to be failing. The associated documentation examples test, which is a copy/paste of the actual shouldly unit test is not behaving as expected. Even though the shouldly unit test seems to be working fine. Not sure why. Will investigate later, but if you have any clues that would be great.

**Comment by JosephWoodward** [comment]
Thanks for doing that @chaitanyagurrapu. I had exactly the same issue with the same test failing last night whilst I was sorting out another PR. I re-ran the test it seemed to run without any problems which was odd.

Is the test repeatedly failing for you? I'd be interested in seeing the output you're getting.

**Comment by chaitanyagurrapu** [comment]
Fails pretty consistently for me. I am using the ms test runner that comes with visual studio rather than the resharper or any other third party version. I am guessing that is the test that is failing in the appveyor CI build as well? This is my output.

image

**Comment by JosephWoodward** [comment]
You're right, I'm getting the same test failing. I must be getting confused with another test I had that was temporarily failing. I'll raise this as an issue.

**Comment by chaitanyagurrapu** [comment]
Found the problem and fixed it @JosephWoodward

**Comment by JosephWoodward** [comment]
Oh amazing! Nice one! :+1:

**Comment by JosephWoodward** [comment]
There we go, all merged. Thanks so much for that :)

**Pull request merged**
