### PR TITLE
Initial attempt at getting 'DynamicShould' working again.

### PR DESCRIPTION
**Pull request by chaitanyagurrapu**
Re visiting issue #145 again.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
I have submitted a PR to your branch fixing a bug which means both the with and without source are using source.

**Comment by chaitanyagurrapu** [comment]
I've updated the PR so that shouldly itself doesn't throw if there is no stacktrace/source code.

**Comment by JakeGinnivan** [comment]
Thanks heaps for getting this working again :)

If you have time docs for DynamicShould would be amazing. All good if not

**Comment by JakeGinnivan** [comment]
Rebased and put up #358 instead of this

**Comment by chaitanyagurrapu** [comment]
@JakeGinnivan  no worries. Will submit a PR with document updates soon.

**Pull request closed without merging**
