### PR TITLE
Refactor ShouldThrowAsync for cancellation handing and add test

### PR DESCRIPTION
**Pull request by adamhathcock**
First time to contribute here.

Looking at solving: https://github.com/shouldly/shouldly/issues/457

Might have issues as I couldn't compile all target frameworks on my mac.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Also probably solves: https://github.com/shouldly/shouldly/issues/471

**Comment by JosephWoodward** [comment]
Sorry for the late reply, thanks for this!

**Comment by JosephWoodward** [comment]
I'll fix the merge conflict then get it out in the next release.

**Comment by colinangusmackay** [comment]
Is there a time-frame for this to put pushed out to NuGet? The last package that I can see there was November 2018, and this was merged in to Master in June 2019.

**Comment by JosephWoodward** [comment]
Hi @colinangusmackay 

There's currently a [4.0.0 beta](https://www.nuget.org/packages/Shouldly/4.0.0-beta0002) that doesn't introduce any major breaking changes that will include this.

**Comment by alexnnenn** [comment]
I've just tried testing call of function Foo and got different behaviour in test, depending on what variant I use:
```
private static async Task Foo()
{
    await Task.Yield();
    throw new OperationCanceledException();
}

private static async Task ShoudlyVariant2(Type exceptionType)
{
    try
    {
        var exception = await Should.ThrowAsync(Foo, exceptionType);
        Console.WriteLine("ShoudlyV2: " + exception.GetType());
    }
    catch(ShouldAssertException s) when (s.Message.Contains("but did not"))
    {
        Console.WriteLine("Variant 2 did not got " + exceptionType.Name);
    }
}

// manual variant
try
{
    await Foo();
}
catch (Exception x)
{
    Console.WriteLine("Manual:" + x.GetType());
}

// Shoudly variant 1
var exceptionV1 = await Should.ThrowAsync<Exception>(Foo);
Console.WriteLine("ShoudlyV1: " + exceptionV1.GetType());

// Shoudly variant 2
await ShoudlyVariant2(typeof(Exception));
await ShoudlyVariant2(typeof(TaskCanceledException));
await ShoudlyVariant2(typeof(OperationCanceledException));
```

The output is:
```
Manual: System.OperationCanceledException
ShoudlyV1: System.Threading.Tasks.TaskCanceledException
Variant 2 did not got Exception
Variant 2 did not got TaskCanceledException
Variant 2 did not got OperationCanceledException
```

I've expected that It will be OperationCanceledException in all variants. It seems, that ThrowAsync still works wrong in case of canceled task.

I've used latest available release version 4.0.3.

**Comment by sungam3r** [comment]
@alexnnenn Worth to open new issue. This one may be lost.

**Pull request merged**
