### PR TITLE
Additional Information in Shouldly methods

### LINKED ISSUE #190: Allow custom/additional message to ShouldlyMessage
I think this is related to #52 but figured I'd like to add it anyway.

I'd **really** like a way to provide a custom message to the 'assert' that is executed.

Scenario:

> I am doing a HTTP Request, I expect an `OK` response, I get `Internal Server Error`. I'd like to add to the message the server response.

Here's a sample of how I'd see the API working:

    [Fact]
    public async Task Should_return_OK() {
        var response = await GetAsync("/api/something");
        
        response.StatusCode.ShouldBe(HttpStatusCode.OK, () => response.Content.ReadAsStringAsync().Result);
    }

Notice the use of the lambda for the additional message, this prevents the code from being executed unless the Should fails, so if you're doing something complex or that has side effects (ie - reading the a HTTP response) it will only be done if needed.

The invocation of the lambda should be in a `try/catch` itself and if it throws just do a `Debug.WriteLine` with the exception (or something similar) and add something to the output message that the additional message failed.

### PR DESCRIPTION
**Pull request by JakeGinnivan**
This PR will fix #190 and #169 by allowing you to specify additional information in Shouldly methods. For example:

`type.IsSealed.ShouldBe(false, "type is " + type.FullName);`. When it fails it will produce an error message of:

```
type.IsSealed should be false but was true

Additional info:
type is MyNamespace.MyType
```

Each shouldly method should have the following overloads:

```
.ShouldBe(this object actual, object expected)
.ShouldBe(this object actual, object expected, string customMessage)
.ShouldBe(this object actual, object expected, Func<string> customMessage)
```
With `.ShouldBe(this object actual, object expected, Func<string> customMessage)` being the method with the implementation, other overloads should defer to it. 

## Todo
 - [x] Extend ShouldlyCoreExtensions.cs (pre-requisite to others)
 - [x] Extend ShouldBeTestExtensions.cs
 - [x] Extend ShouldBeDateTimeTestExtensions.cs
 - [x] Extend ShouldBeNumericTestExtensions.cs
 - [x] Extend ShouldBeStringTestExtensions.cs
 - [x] Extend ShouldBeDictionaryTestExtensions.cs
 - [x] Extend ShouldBeEnumerableTestExtensions.cs
 - [x] Extend ShouldBeGtLtTestExtensions.cs
 - [x] Extend ShouldBeRangeTestExtensions.cs
 - [x] Extend ShouldBeTypeTestExtensions.cs
 - [x] Extend ShouldCompleteInExtensions.cs

Anyone feel free to pitch in and take one of the classes which needs to be updated, just put a comment. Submit PR's to this branch

When creating the overloads, update tests to use the `Func<string> customMessage` version

// @aaronpowell, @raybooysen, @fekberg, @robdmoore, @PureKrome, @pawelpabich, @JoeMighty

### CODE REVIEW

**Comment by mleech** [comment]
Hey @JakeGinnivan,
I'd already started playing with a fix for this (but without the lambda overloads) - I'll tackle the first 2 classes (ShouldlyCoreExtensions & ShouldBeTestExtensions)

**Comment by aaronpowell** [comment]
Well I guess I didn't need to retarget my PR, it looks like what I'd done is already in there :stuck_out_tongue:

**Comment by JakeGinnivan** [comment]
yeah, @mleech beat you to it

**Comment by JoeMighty** [comment]
I've just committed an update for `ShouldBeDateTimeTestExtensions.cs`. (Pull request [#199](https://github.com/shouldly/shouldly/pull/199))

Hopefully I'll be able to do a few more tonight!

**Comment by JoeMighty** [comment]
`ShouldBeNumericTestExtensions.cs` has now been sorted and the tests have been updated. This is also in PR #199.

**Comment by JakeGinnivan** [comment]
All pr's merged and this branch is now up to date with master again.

**Comment by JoeMighty** [comment]
Great, hopefully get one or two more done tonight and /or during tomorrow's lunch break.

**Comment by JoeMighty** [comment]
I've made a start on `ShouldBeStringTestExtensions.cs` and the tests relating to it.

**Comment by JoeMighty** [comment]
Just created a PR (#202) for ShouldBeStringTestExtensions

**Comment by JoeMighty** [comment]
I've sorted `DictionaryTestExtensions.cs` and will create a PR for later on today (once I've figured out what's up with my feature branch's git history).

**Comment by JakeGinnivan** [comment]
If you need a hand with the git side of things let me know

**Comment by JoeMighty** [comment]
Thank you Jake. I don't know what I've done; I thought I'd synced my fork synced my fork by following [this tutorial](https://help.github.com/articles/syncing-a-fork/) but after having a look at the differences between my feature branch when I went create a pull request the upstream seems like there's a number of unrelated differences.

**Comment by JakeGinnivan** [comment]
Ok, I think what has happened is I have rebased some of your pull requests as they couldn't be merged so there are duplicated commits. This is the reason for the 'never commit to master' rule. Your master is always clean and safe to branch off.

Anyways, lets fix :) I am assuming your git is setup with `origin` being your fork and `upstream` being the main repo, change the remote names if that is not the case.

```
git fetch upstream
git checkout master
git reset --hard upstream/master  # Make your local master point at same commit as upstream/master
git checkout AdditionalInfoMessages
git reset --hard upstream/AdditionalInfoMessages # also fix your local AdditionalInfoMessages branch
```

Now your master and AdditionalInfoMessages branches are good to go. You can `fetch upstream`/`merge upstream/master --ff-only` to bring them up to date. the `--ff-only` tells git that it should never create a merge commit, this means you get an error if your histories have diverged or you have accidently commited to your local branches.

There are two ways to fix your `DictionaryTestExtensions` branch. First is cherry picking

```
git checkout AdditionalInfoMessages
git checkout -b DictionaryTestExtensions2
git cherry-pick 3470096f592f01dad0c99e06dfb6b9fd2f585672 --commit   # this is the commit sha which you did the work in
git push origin DictionaryTestExtensions2  # do the PR off the new fixed branch
```

The other option is interactive rebase. This allows you to rewrite history with full control.

```
git checkout DictionaryTestExtensions
git rebase upstream/AdditionalInfoMessages -i    # -i for interactive rebase
# this should pop up a text editor of some sort, simply delete or comment out the lines which are commits which you don't want 
# which is basically everything except Added custom messages to ShouldBeDictionaryTestExtensions and updated unit tests
git push origin DictionaryTestExtension -f # -f for force push as you have rewritten history
```

Hope that helps

**Comment by JoeMighty** [comment]
Wow, thank you for the thorough write up - that's sorted the problem (I used cherry pick in this instance as it was a single commit, but I presume interactive base (which I've dabbled with after watching that video you recommended) is more suitable for managing multiple commits?). Since watching that video you recommend it's slowly beginning to piece together bit by bit. 

I take it at this point, having followed your instruction above, my local repository is all up to date and in order to update my forked repository I should now force push my local repository to my forked repo?

**Comment by JakeGinnivan** [comment]
> I used cherry pick in this instance as it was a single commit, but I presume interactive rebase is more suitable for managing multiple commits?
Exactly, interactive rebase also allows you to squash specific commits into the previous as well as stop on a specific commit, make changes, then continue the rebase. It basically allows you to do anything you want :)

> I should now force push my local repository to my forked repo

Yep

**Comment by JoeMighty** [comment]
Awesome, that did the job! Thanks once again for all of your help :) :+1:

**Comment by JakeGinnivan** [comment]
No worries, thanks for the pull requests :)

**Comment by robertlyson** [comment]
Let me help you guys with `ShouldBeEnumerableTestExtensions` :)

**Comment by JakeGinnivan** [comment]
Great, let me know if you need a hand @robertlyson

**Comment by JoeMighty** [comment]
ShouldBeGtLtTestExtensions.cs is sorted (#208).

**Comment by robertlyson** [comment]
I'll handle `ShouldBeRangeTestExtensions`.

**Pull request merged**
