### PR TITLE
#217 implement NotThrowAsync

### PR DESCRIPTION
**Pull request by hossambarakat**
Implemented Should.NotThrowAsync(Task) and Should.NotThrowAsync(Func<Task>)

### CODE REVIEW

**Comment by hossambarakat** [comment]
@JosephWoodward Would like to get your feedback if this pull request will be reviewed and eventually merged :)

**Comment by JosephWoodward** [comment]
It will be merged, just trying to get the tests working against .NET Standard then going to look at merging this.

**Comment by hossambarakat** [comment]
@JosephWoodward Could you please have a look on this PR

**Comment by mikesigs** [comment]
Would love to see this merged in 2020 :P

**Comment by AlexHaigh** [comment]
This is undocumented on the website

**Pull request merged**
