### PR TITLE
fix ShouldAllBe message generator

### PR DESCRIPTION
**Pull request by cottsak**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Looks good

**Comment by JakeGinnivan** [comment]
Should it be `do not` rather than `does not`

**Comment by JakeGinnivan** [comment]
`return "new[] { 1, 2, 3 } should satisfy the condition (x < 2) but [2,3] does not"`

Does implies something you passed, do implies those are the items which do not match?

**Comment by cottsak** [comment]
@JakeGinnivan yep! I like "do" better

**Comment by JakeGinnivan** [comment]
Great

**Comment by dennisroche** [comment]
Fixes https://github.com/shouldly/shouldly/issues/150

**Pull request merged**
