### PR TITLE
#172 issue bug fix

### PR DESCRIPTION
**Pull request by YogirajA**
I was able to resolve the problem of failing test for #172. All the tests are now passing.  Please check it out and let me know if something needs to change.

### CODE REVIEW

**Comment by YogirajA** [comment]
@JakeGinnivan I dont know why there is so many old commits showing up in the pull request. My history just shows sync and issue fixed one.

**Comment by JakeGinnivan** [comment]
I can fix that, no worries

**Comment by JakeGinnivan** [comment]
When I fix it I will post the git commands which will fix your repo too

**Comment by JakeGinnivan** [comment]
@YogirajA thanks heaps for the investigation and fixing the issue, it works great.

I did an interactive rebase and removed all the commits except for the commit which fixed the issue. I also just added another commit to fix the error message so it is nicer.

To fix your master go this

```
git fetch upstream
git checkout master
git reset --hard upstream/master
```

That will give you a clean master to work from. Then use feature branches for features. Before you start a feature:

```
git checkout master
git fetch upstream
git merge upstream/master --ff-only     #if this fails you might have accidentally committed something to master
git checkout feature/myFeatureBranch
```

Then when you are ready to submit your pull request you can rebase your branch instead of doing merges to keep it up to date

```
git fetch upstream
git rebase upstream/master
git push origin feature/myFeatureBranch -f
```

Hope that helps. Thanks again!

**Comment by YogirajA** [comment]
@JakeGinnivan thanks for the detailed instructions!

**Pull request closed without merging**
